more adjustments for Lua-5.2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -304,11 +304,11 @@ then
 elif [ x"$TARGET" = x"mingw" -a -r /usr/local/cross-tools/i386-mingw32/include/lua.h ]
 then
   LUA_CFLAGS="-I/usr/local/cross-tools/i386-mingw32/include"
-  LUA_LDFLAGS="-L/usr/local/cross-tools/i386-mingw32/lib -llua51"
+  LUA_LDFLAGS="-L/usr/local/cross-tools/i386-mingw32/lib -llua52"
 elif [ x"$SYSTEM" = x"mingw" ]
 then
   LUA_CFLAGS=""
-  LUA_LDFLAGS="-llua51"
+  LUA_LDFLAGS="-llua52"
 elif [ x"${hosttype}" = x"x86" ] # private hack
 then
   LUA_CFLAGS=""
@@ -316,12 +316,12 @@ then
 elif [ x"$STATIC_LUA" = x"yes" ]
 then
   LUA_CFLAGS=""
-  if [ -a -r /usr/lib/liblua5.1.a ]
+  if [ -a -r /usr/lib/liblua5.2.a ]
   then
-    LUA_LDFLAGS="/usr/lib/liblua5.1.a -lm -Wl,-E"
-  elif [ -r /usr/lib/liblua-5.1.a ]
+    LUA_LDFLAGS="/usr/lib/liblua5.2.a -lm -Wl,-E"
+  elif [ -r /usr/lib/liblua-5.2.a ]
   then
-    LUA_LDFLAGS="/usr/lib/liblua-5.1.a -lm -Wl,-E"
+    LUA_LDFLAGS="/usr/lib/liblua-5.2.a -lm -Wl,-E"
   elif [ -r /usr/lib/liblua.a ]
   then
     LUA_LDFLAGS="/usr/lib/liblua.a -lm -Wl,-E"
@@ -332,23 +332,23 @@ then
     echo "static Lua not found" 1>&2
     exit 1
   fi
-elif pkg-config --exists lua-5.1  # FreeBSD 8.0
+elif pkg-config --exists lua-5.2  # FreeBSD 8.0
 then
-  LUA_CFLAGS=`pkg-config lua-5.1 --cflags`
-  LUA_LDFLAGS=`pkg-config lua-5.1 --libs`
-elif pkg-config --exists lua5.1  # Debian
+  LUA_CFLAGS=`pkg-config lua-5.2 --cflags`
+  LUA_LDFLAGS=`pkg-config lua-5.2 --libs`
+elif pkg-config --exists lua5.2  # Debian
 then
-  LUA_CFLAGS=`pkg-config lua5.1 --cflags`
-  LUA_LDFLAGS=`pkg-config lua5.1 --libs`
+  LUA_CFLAGS=`pkg-config lua5.2 --cflags`
+  LUA_LDFLAGS=`pkg-config lua5.2 --libs`
 elif pkg-config --exists lua  # Fedora
 then
   # hope it's the correct version
   LUA_CFLAGS=`pkg-config lua --cflags`
   LUA_LDFLAGS=`pkg-config lua --libs`
-elif [ -r /usr/include/lua5.1/lua.h -a /usr/lib/liblua5.1.so ]
+elif [ -r /usr/include/lua5.2/lua.h -a /usr/lib/liblua5.2.so ]
 then
-  LUA_CFLAGS="-I/usr/include/lua5.1"
-  LUA_LDFLAGS="-llua5.1"
+  LUA_CFLAGS="-I/usr/include/lua5.2"
+  LUA_LDFLAGS="-llua5.2"
 elif [ -r /usr/include/lua.h -a /usr/lib/liblua.a ]
 then
   LUA_CFLAGS=""
@@ -359,7 +359,7 @@ then
   LUA_LDFLAGS="-llua -lm -Wl,-E"
 elif [ x"$NO_LUA" != x"yes" ]
 then
-  echo "Lua 5.1 not found" 1>&2
+  echo "Lua 5.2 not found" 1>&2
   echo "use --disable-lua to build without Lua" 1>&2
   exit 1
 fi
