configure: --with-static-lua

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -28,6 +28,7 @@ FORCE_ICONV=
 WCHAR_ENCODING=
 SDL_IMAGE="yes"
 LINK_SDL_IMAGE="no"
+STATIC_LUA="no"
 
 # clear some things potentially inherited from environment.
 srcdir=
@@ -94,6 +95,7 @@ while [ x"$1" != x ] ; do
 		echo "  --with-oldsdl         support for older SDL versions on target machine"
 		echo "  --with-iconv[=enc]    force use of external iconv (normally not needed)"
 		echo "  --with-sdl-iconv=enc  set encoding for wchar_t when SDL's iconv is used"
+		echo "  --with-static-lua     try to link Lua statically"
 		echo "  --disable-audio       disable audio support"
 		echo "  --disable-sdl-image   disable support for SDL_image completely"
 		echo "  --enable-link-sdl-image link directly to SDL_image"
@@ -158,6 +160,7 @@ while [ x"$1" != x ] ; do
 	--with-iconv) FORCE_ICONV="yes" ;;
 	--with-iconv=*) FORCE_ICONV="yes"; WCHAR_ENCODING=${optarg} ;;
 	--with-iconv) FORCE_ICONV="yes" ;;
+	--with-static-lua) STATIC_LUA="yes" ;;
 	--enable-link-sdl-image | \
 	--enable-link-sdl-image=yes) LINK_SDL_IMAGE="yes" ;;
 	--enable-link-sdl-image=no | \
@@ -319,6 +322,26 @@ then
 else
   echo "Lua 5.1 not found" 1>&2
   exit 1
+fi
+
+if [ x"$STATIC_LUA" = x"yes" -a x"${hosttype}" != x"x86" ]
+then
+  if [ -r /usr/lib/liblua5.1.a ]
+  then
+    LUA_LDFLAGS="/usr/lib/liblua5.1.a -lm"
+  elif [ -r /usr/lib/liblua-5.1.a ]
+  then
+    LUA_LDFLAGS="/usr/lib/liblua-5.1.a -lm"
+  elif [ -r /usr/lib/liblua.a ]
+  then
+    LUA_LDFLAGS="/usr/lib/liblua.a -lm"
+  elif [ -r /usr/local/lib/liblua.a ]
+  then
+    LUA_LDFLAGS="/usr/local/lib/liblua.a -lm"
+  else
+    echo "static Lua not found" 1>&2
+    exit 1
+  fi
 fi
 
 ########################################################################################
