configure: finding Lua in one if-chain

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -296,9 +296,7 @@ then
   test x"$TARGET" = x"mingw" && TARGET="mingw-nolua" || TARGET="nolua"
   LUA_CFLAGS=""
   LUA_LDFLAGS=""
-fi
-
-if [ x"$TARGET" = x"mingw" -a -r /usr/local/cross-tools/i386-mingw32/include/lua.h ]
+elif [ x"$TARGET" = x"mingw" -a -r /usr/local/cross-tools/i386-mingw32/include/lua.h ]
 then
   LUA_CFLAGS="-I/usr/local/cross-tools/i386-mingw32/include"
   LUA_LDFLAGS="-L/usr/local/cross-tools/i386-mingw32/lib -llua51"
@@ -310,6 +308,24 @@ elif [ x"${hosttype}" = x"x86" ] # private hack
 then
   LUA_CFLAGS="-I/usr/local/include/lua5.1"
   LUA_LDFLAGS="-llua -lm -Wl,-E" # static lib!
+elif [ x"$STATIC_LUA" = x"yes" ]
+then
+  if [ -a -r /usr/lib/liblua5.1.a ]
+  then
+    LUA_LDFLAGS="/usr/lib/liblua5.1.a -lm -Wl,-E"
+  elif [ -r /usr/lib/liblua-5.1.a ]
+  then
+    LUA_LDFLAGS="/usr/lib/liblua-5.1.a -lm -Wl,-E"
+  elif [ -r /usr/lib/liblua.a ]
+  then
+    LUA_LDFLAGS="/usr/lib/liblua.a -lm -Wl,-E"
+  elif [ -r /usr/local/lib/liblua.a ]
+  then
+    LUA_LDFLAGS="/usr/local/lib/liblua.a -lm -Wl,-E"
+  else
+    echo "static Lua not found" 1>&2
+    exit 1
+  fi
 elif pkg-config --exists lua-5.1  # FreeBSD 8.0
 then
   LUA_CFLAGS=`pkg-config lua-5.1 --cflags`
@@ -342,25 +358,6 @@ then
   exit 1
 fi
 
-if [ x"$STATIC_LUA" = x"yes" -a x"${hosttype}" != x"x86" ]
-then
-  if [ -r /usr/lib/liblua5.1.a ]
-  then
-    LUA_LDFLAGS="/usr/lib/liblua5.1.a -lm -Wl,-E"
-  elif [ -r /usr/lib/liblua-5.1.a ]
-  then
-    LUA_LDFLAGS="/usr/lib/liblua-5.1.a -lm -Wl,-E"
-  elif [ -r /usr/lib/liblua.a ]
-  then
-    LUA_LDFLAGS="/usr/lib/liblua.a -lm -Wl,-E"
-  elif [ -r /usr/local/lib/liblua.a ]
-  then
-    LUA_LDFLAGS="/usr/local/lib/liblua.a -lm -Wl,-E"
-  else
-    echo "static Lua not found" 1>&2
-    exit 1
-  fi
-fi
 
 ########################################################################################
 
