configure: Make Lua version configurable

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,7 @@
 #!/bin/sh
 # configure script for AKFAvatar - library and program for using an avatar
-# Copyright (C) 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2015 Andreas K. Foerster
+# Copyright (C) 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2015
+# Andreas K. Foerster
 # Copyright (C) 2003, 2004, 2005, 2006, 2007, 2008 Antonio Diaz Diaz.
 #
 # This configure script is free software; you have unlimited permission
@@ -28,6 +29,8 @@ USE_LINUXFB="no"
 USE_SDL="yes"
 SDL_IMAGE="yes"
 LINK_SDL_IMAGE="no"
+LUA_MAJOR=5
+LUA_MINOR=3
 NO_LUA="no"
 STATIC_LUA="no"
 NO_DEPRECATED="no"
@@ -409,18 +412,18 @@ then
   case ${hosttype} in
     x86_64*-mingw* | amd64*-mingw*)
       LUA_CFLAGS="-I/usr/local/x86_64-w64-mingw32/include"
-      LUA_LDFLAGS="-L/usr/local/x86_64-w64-mingw32/lib -llua53"
+      LUA_LDFLAGS="-L/usr/local/x86_64-w64-mingw32/lib -llua$LUA_MAJOR$LUA_MINOR"
       ;;
 
     *mingw* | *MINGW*)
       if [ -d /usr/local/i686-w64-mingw32/include ]
       then
         LUA_CFLAGS="-I/usr/local/i686-w64-mingw32/include"
-        LUA_LDFLAGS="-L/usr/local/i686-w64-mingw32/lib -llua53"
+        LUA_LDFLAGS="-L/usr/local/i686-w64-mingw32/lib -llua$LUA_MAJOR$LUA_MINOR"
       elif [ -d /usr/local/cross-tools/i386-mingw32/include ]
       then
         LUA_CFLAGS="-I/usr/local/cross-tools/i386-mingw32/include"
-        LUA_LDFLAGS="-L/usr/local/cross-tools/i386-mingw32/lib -llua53"
+        LUA_LDFLAGS="-L/usr/local/cross-tools/i386-mingw32/lib -llua$LUA_MAJOR$LUA_MINOR"
       fi
       ;;
 
@@ -433,7 +436,7 @@ then
       LUA_CFLAGS=""
       if [ x"$SYSTEM" = x"mingw" ]
       then
-        LUA_LDFLAGS="-llua53"
+        LUA_LDFLAGS="-llua$LUA_MAJOR$LUA_MINOR"
       else
         LUA_LDFLAGS="-llua -lm -ldl -Wl,-E" # assume static lib!
       fi
@@ -442,50 +445,51 @@ then
 elif [ x"$STATIC_LUA" = x"yes" ]
 then
   LUA_CFLAGS=""
-  if [ -r /usr/lib/liblua5.3.a ]
+  if [ -r "/usr/lib/liblua${LUA_MAJOR}.${LUA_MINOR}.a" ]
   then
-    LUA_LDFLAGS="/usr/lib/liblua5.3.a -lm -ldl -Wl,-E"
-  elif [ -r /usr/lib/liblua-5.3.a ]
+    LUA_LDFLAGS="/usr/lib/liblua${LUA_MAJOR}.${LUA_MINOR}.a -lm -ldl -Wl,-E"
+  elif [ -r "/usr/lib/liblua-${LUA_MAJOR}.${LUA_MINOR}.a" ]
   then
-    LUA_LDFLAGS="/usr/lib/liblua-5.3.a -lm -ldl -Wl,-E"
-  elif [ -r /usr/lib/liblua.a ]
+    LUA_LDFLAGS="/usr/lib/liblua-${LUA_MAJOR}.${LUA_MINOR}.a -lm -ldl -Wl,-E"
+  elif [ -r "/usr/lib/liblua.a" ]
   then
     LUA_LDFLAGS="/usr/lib/liblua.a -lm -ldl -Wl,-E"
-  elif [ -r /usr/local/lib/liblua.a ]
+  elif [ -r "/usr/local/lib/liblua.a" ]
   then
     LUA_LDFLAGS="/usr/local/lib/liblua.a -lm -ldl -Wl,-E"
   else
     echo "static Lua not found" 1>&2
     exit 1
   fi
-elif pkg-config --exists lua-5.3  # FreeBSD 8.0
+elif pkg-config --exists "lua-${LUA_MAJOR}.${LUA_MINOR}"  # FreeBSD 8.0
 then
-  LUA_CFLAGS=`pkg-config lua-5.3 --cflags`
-  LUA_LDFLAGS=`pkg-config lua-5.3 --libs`
-elif pkg-config --exists lua5.3  # Debian
+  LUA_CFLAGS=`pkg-config "lua-${LUA_MAJOR}.${LUA_MINOR}" --cflags`
+  LUA_LDFLAGS=`pkg-config "lua-${LUA_MAJOR}.${LUA_MINOR}" --libs`
+elif pkg-config --exists "lua${LUA_MAJOR}.${LUA_MINOR}"  # Debian
 then
-  LUA_CFLAGS=`pkg-config lua5.3 --cflags`
-  LUA_LDFLAGS=`pkg-config lua5.3 --libs`
+  LUA_CFLAGS=`pkg-config "lua${LUA_MAJOR}.${LUA_MINOR}" --cflags`
+  LUA_LDFLAGS=`pkg-config "lua${LUA_MAJOR}.${LUA_MINOR}" --libs`
 elif pkg-config --exists lua  # Fedora
 then
   # hope it's the correct version
   LUA_CFLAGS=`pkg-config lua --cflags`
   LUA_LDFLAGS=`pkg-config lua --libs`
-elif [ -r /usr/include/lua5.3/lua.h -a /usr/lib/liblua5.3.so ]
+elif [ -r "/usr/include/lua${LUA_MAJOR}.${LUA_MINOR}/lua.h" \
+       -a "/usr/lib/liblua${LUA_MAJOR}.${LUA_MINOR}.so" ]
 then
-  LUA_CFLAGS="-I/usr/include/lua5.3"
-  LUA_LDFLAGS="-llua5.3"
-elif [ -r /usr/include/lua.h -a /usr/lib/liblua.a ]
+  LUA_CFLAGS="-I/usr/include/lua${LUA_MAJOR}.${LUA_MINOR}"
+  LUA_LDFLAGS="-llua${LUA_MAJOR}.${LUA_MINOR}"
+elif [ -r "/usr/include/lua.h" -a "/usr/lib/liblua.a" ]
 then
   LUA_CFLAGS=""
   LUA_LDFLAGS="-llua -lm -ldl -Wl,-E"
-elif [ -r /usr/local/include/lua.h -a /usr/local/lib/liblua.a ]
+elif [ -r "/usr/local/include/lua.h" -a "/usr/local/lib/liblua.a" ]
 then
   LUA_CFLAGS=""
   LUA_LDFLAGS="-llua -lm -ldl -Wl,-E"
 elif [ x"$NO_LUA" != x"yes" ]
 then
-  echo "Lua 5.2 not found" 1>&2
+  echo "Lua-${LUA_MAJOR}.${LUA_MINOR} not found" 1>&2
   echo "use --disable-lua to build without Lua" 1>&2
   exit 1
 fi
@@ -679,6 +683,8 @@ INSTALL = ${INSTALL}
 LDCONFIG = ${LDCONFIG}
 SDL_CFLAGS = ${SDL_CFLAGS}
 SDL_LDFLAGS = ${SDL_LDFLAGS}
+LUA_MAJOR = ${LUA_MAJOR}
+LUA_MINOR = ${LUA_MINOR}
 LUA_CFLAGS = ${LUA_CFLAGS}
 LUA_LDFLAGS = ${LUA_LDFLAGS}
 AWK = ${AWK}
@@ -694,13 +700,13 @@ EOF
 
 case ${SYSTEM} in
  mingw)
-   echo 'lua_dll = $(srcdir)/misc/$(ARCH)/lua53.dll' >> Makefile
+   echo "lua_dll = ${srcdir}/misc/${ARCH}/lua${LUA_MAJOR}${LUA_MINOR}.dll" >> Makefile
 
    if [ x"$SDL_CONFIG" = x"sdl2-config" ]
    then
-     echo 'sdl_dll = $(srcdir)/misc/$(ARCH)/SDL2.dll' >> Makefile
+     echo "sdl_dll = ${srcdir}/misc/${ARCH}/SDL2.dll" >> Makefile
    else
-     echo 'sdl_dll = $(srcdir)/misc/$(ARCH)/SDL.dll' >> Makefile
+     echo "sdl_dll = ${srcdir}/misc/${ARCH}/SDL.dll" >> Makefile
    fi
 
    cat ${srcdir}/mingw/Makefile.in >> Makefile
@@ -750,4 +756,3 @@ EOF
 echo '*'
 echo '* OK. Now you can run "make" to build the binaries.'
 echo '*'
-
